/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SignupBuilderProps } from "./components/signup-form/interface";
export { SignupBuilderProps } from "./components/signup-form/interface";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SecondTemplate {
    }
    interface SignupComponent {
        "data": SignupBuilderProps;
    }
}
export interface SignupComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSignupComponentElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSecondTemplateElement extends Components.SecondTemplate, HTMLStencilElement {
    }
    var HTMLSecondTemplateElement: {
        prototype: HTMLSecondTemplateElement;
        new (): HTMLSecondTemplateElement;
    };
    interface HTMLSignupComponentElement extends Components.SignupComponent, HTMLStencilElement {
    }
    var HTMLSignupComponentElement: {
        prototype: HTMLSignupComponentElement;
        new (): HTMLSignupComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "second-template": HTMLSecondTemplateElement;
        "signup-component": HTMLSignupComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SecondTemplate {
    }
    interface SignupComponent {
        "data"?: SignupBuilderProps;
        "onMyChange"?: (event: SignupComponentCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "second-template": SecondTemplate;
        "signup-component": SignupComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "second-template": LocalJSX.SecondTemplate & JSXBase.HTMLAttributes<HTMLSecondTemplateElement>;
            "signup-component": LocalJSX.SignupComponent & JSXBase.HTMLAttributes<HTMLSignupComponentElement>;
        }
    }
}
